// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package dbgen

import (
	"database/sql"
)

type File struct {
	ID          int64          `json:"id"`
	Path        string         `json:"path"`
	Inode       int64          `json:"inode"`
	Device      int64          `json:"device"`
	Mtime       int64          `json:"mtime"`
	SizeBytes   int64          `json:"size_bytes"`
	ContentHash sql.NullString `json:"content_hash"`
	IndexedAt   int64          `json:"indexed_at"`
}

type FileTag struct {
	FileID int64 `json:"file_id"`
	TagID  int64 `json:"tag_id"`
}

type Metadata struct {
	FileID int64  `json:"file_id"`
	Key    string `json:"key"`
	Value  string `json:"value"`
	Source string `json:"source"`
}

type MetadataFt struct {
	Value string `json:"value"`
}

type SchemaMigration struct {
	Version   int64 `json:"version"`
	AppliedAt int64 `json:"applied_at"`
}

type SidecarDatum struct {
	Inode  int64  `json:"inode"`
	Device int64  `json:"device"`
	Data   string `json:"data"`
}

type Tag struct {
	ID          int64  `json:"id"`
	Name        string `json:"name"`
	Cardinality int64  `json:"cardinality"`
}

type TagOverride struct {
	FileID       int64  `json:"file_id"`
	TagID        int64  `json:"tag_id"`
	RuleName     string `json:"rule_name"`
	SuppressedAt int64  `json:"suppressed_at"`
}

type TagProvenance struct {
	FileID int64  `json:"file_id"`
	TagID  int64  `json:"tag_id"`
	Source string `json:"source"`
	SetAt  int64  `json:"set_at"`
}
