// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package dbgen

import (
	"context"
)

type Querier interface {
	AddFileTag(ctx context.Context, arg AddFileTagParams) error
	ClearFileTags(ctx context.Context, fileID int64) error
	DeleteFile(ctx context.Context, path string) error
	DeleteMeta(ctx context.Context, arg DeleteMetaParams) error
	DeleteSidecar(ctx context.Context, arg DeleteSidecarParams) error
	DeleteStaleFiles(ctx context.Context, arg DeleteStaleFilesParams) error
	GetFileIDByPath(ctx context.Context, path string) (int64, error)
	GetFileMeta(ctx context.Context, fileID int64) ([]GetFileMetaRow, error)
	GetFileSummary(ctx context.Context, path string) (GetFileSummaryRow, error)
	GetFileTags(ctx context.Context, fileID int64) ([]string, error)
	GetStats(ctx context.Context) (GetStatsRow, error)
	GetTagOverrides(ctx context.Context, fileID int64) ([]GetTagOverridesRow, error)
	ListAllTags(ctx context.Context) ([]string, error)
	ListFilePaths(ctx context.Context) ([]string, error)
	ListFileTagPairs(ctx context.Context) ([]ListFileTagPairsRow, error)
	ReadSidecar(ctx context.Context, arg ReadSidecarParams) (string, error)
	RemoveFileTag(ctx context.Context, arg RemoveFileTagParams) error
	SetTagProvenance(ctx context.Context, arg SetTagProvenanceParams) error
	UpsertFile(ctx context.Context, arg UpsertFileParams) (int64, error)
	UpsertMeta(ctx context.Context, arg UpsertMetaParams) error
	UpsertTag(ctx context.Context, name string) (int64, error)
	WriteSidecar(ctx context.Context, arg WriteSidecarParams) error
}

var _ Querier = (*Queries)(nil)
