// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: query.sql

package dbgen

import (
	"context"
)

const addFileTag = `-- name: AddFileTag :exec
INSERT OR IGNORE INTO file_tags(file_id, tag_id) VALUES (?, ?)
`

type AddFileTagParams struct {
	FileID int64 `json:"file_id"`
	TagID  int64 `json:"tag_id"`
}

func (q *Queries) AddFileTag(ctx context.Context, arg AddFileTagParams) error {
	_, err := q.db.ExecContext(ctx, addFileTag, arg.FileID, arg.TagID)
	return err
}

const clearFileTags = `-- name: ClearFileTags :exec
DELETE FROM file_tags WHERE file_id = ?
`

func (q *Queries) ClearFileTags(ctx context.Context, fileID int64) error {
	_, err := q.db.ExecContext(ctx, clearFileTags, fileID)
	return err
}

const deleteFile = `-- name: DeleteFile :exec
DELETE FROM files WHERE path = ?
`

func (q *Queries) DeleteFile(ctx context.Context, path string) error {
	_, err := q.db.ExecContext(ctx, deleteFile, path)
	return err
}

const deleteMeta = `-- name: DeleteMeta :exec
DELETE FROM metadata WHERE file_id = ? AND key = ?
`

type DeleteMetaParams struct {
	FileID int64  `json:"file_id"`
	Key    string `json:"key"`
}

func (q *Queries) DeleteMeta(ctx context.Context, arg DeleteMetaParams) error {
	_, err := q.db.ExecContext(ctx, deleteMeta, arg.FileID, arg.Key)
	return err
}

const deleteSidecar = `-- name: DeleteSidecar :exec
DELETE FROM sidecar_data WHERE inode = ? AND device = ?
`

type DeleteSidecarParams struct {
	Inode  int64 `json:"inode"`
	Device int64 `json:"device"`
}

func (q *Queries) DeleteSidecar(ctx context.Context, arg DeleteSidecarParams) error {
	_, err := q.db.ExecContext(ctx, deleteSidecar, arg.Inode, arg.Device)
	return err
}

const deleteStaleFiles = `-- name: DeleteStaleFiles :exec
DELETE FROM files WHERE path LIKE ? AND indexed_at < ?
`

type DeleteStaleFilesParams struct {
	Path      string `json:"path"`
	IndexedAt int64  `json:"indexed_at"`
}

func (q *Queries) DeleteStaleFiles(ctx context.Context, arg DeleteStaleFilesParams) error {
	_, err := q.db.ExecContext(ctx, deleteStaleFiles, arg.Path, arg.IndexedAt)
	return err
}

const getFileIDByPath = `-- name: GetFileIDByPath :one
SELECT id FROM files WHERE path = ?
`

func (q *Queries) GetFileIDByPath(ctx context.Context, path string) (int64, error) {
	row := q.db.QueryRowContext(ctx, getFileIDByPath, path)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const getFileMeta = `-- name: GetFileMeta :many
SELECT key, value, source FROM metadata WHERE file_id = ?
`

type GetFileMetaRow struct {
	Key    string `json:"key"`
	Value  string `json:"value"`
	Source string `json:"source"`
}

func (q *Queries) GetFileMeta(ctx context.Context, fileID int64) ([]GetFileMetaRow, error) {
	rows, err := q.db.QueryContext(ctx, getFileMeta, fileID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetFileMetaRow
	for rows.Next() {
		var i GetFileMetaRow
		if err := rows.Scan(&i.Key, &i.Value, &i.Source); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getFileSummary = `-- name: GetFileSummary :one
SELECT id, mtime, size_bytes FROM files WHERE path = ? LIMIT 1
`

type GetFileSummaryRow struct {
	ID        int64 `json:"id"`
	Mtime     int64 `json:"mtime"`
	SizeBytes int64 `json:"size_bytes"`
}

func (q *Queries) GetFileSummary(ctx context.Context, path string) (GetFileSummaryRow, error) {
	row := q.db.QueryRowContext(ctx, getFileSummary, path)
	var i GetFileSummaryRow
	err := row.Scan(&i.ID, &i.Mtime, &i.SizeBytes)
	return i, err
}

const getFileTags = `-- name: GetFileTags :many
SELECT t.name FROM file_tags ft 
JOIN tags t ON t.id = ft.tag_id 
WHERE ft.file_id = ?
ORDER BY t.name
`

func (q *Queries) GetFileTags(ctx context.Context, fileID int64) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, getFileTags, fileID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var name string
		if err := rows.Scan(&name); err != nil {
			return nil, err
		}
		items = append(items, name)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getStats = `-- name: GetStats :one
SELECT 
    (SELECT COUNT(*) FROM files) as files_count, 
    (SELECT COUNT(*) FROM tags) as tags_count
`

type GetStatsRow struct {
	FilesCount int64 `json:"files_count"`
	TagsCount  int64 `json:"tags_count"`
}

func (q *Queries) GetStats(ctx context.Context) (GetStatsRow, error) {
	row := q.db.QueryRowContext(ctx, getStats)
	var i GetStatsRow
	err := row.Scan(&i.FilesCount, &i.TagsCount)
	return i, err
}

const getTagOverrides = `-- name: GetTagOverrides :many
SELECT t.name, o.rule_name
FROM tag_overrides o
JOIN tags t ON t.id = o.tag_id
WHERE o.file_id = ?
`

type GetTagOverridesRow struct {
	Name     string `json:"name"`
	RuleName string `json:"rule_name"`
}

func (q *Queries) GetTagOverrides(ctx context.Context, fileID int64) ([]GetTagOverridesRow, error) {
	rows, err := q.db.QueryContext(ctx, getTagOverrides, fileID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetTagOverridesRow
	for rows.Next() {
		var i GetTagOverridesRow
		if err := rows.Scan(&i.Name, &i.RuleName); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAllTags = `-- name: ListAllTags :many
SELECT name FROM tags ORDER BY name
`

func (q *Queries) ListAllTags(ctx context.Context) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, listAllTags)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var name string
		if err := rows.Scan(&name); err != nil {
			return nil, err
		}
		items = append(items, name)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFilePaths = `-- name: ListFilePaths :many
SELECT path FROM files ORDER BY path
`

func (q *Queries) ListFilePaths(ctx context.Context) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, listFilePaths)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var path string
		if err := rows.Scan(&path); err != nil {
			return nil, err
		}
		items = append(items, path)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFileTagPairs = `-- name: ListFileTagPairs :many
SELECT f.path, t.name
FROM file_tags ft
JOIN files f ON f.id = ft.file_id
JOIN tags  t ON t.id = ft.tag_id
`

type ListFileTagPairsRow struct {
	Path string `json:"path"`
	Name string `json:"name"`
}

func (q *Queries) ListFileTagPairs(ctx context.Context) ([]ListFileTagPairsRow, error) {
	rows, err := q.db.QueryContext(ctx, listFileTagPairs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListFileTagPairsRow
	for rows.Next() {
		var i ListFileTagPairsRow
		if err := rows.Scan(&i.Path, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const readSidecar = `-- name: ReadSidecar :one
SELECT data FROM sidecar_data WHERE inode = ? AND device = ?
`

type ReadSidecarParams struct {
	Inode  int64 `json:"inode"`
	Device int64 `json:"device"`
}

func (q *Queries) ReadSidecar(ctx context.Context, arg ReadSidecarParams) (string, error) {
	row := q.db.QueryRowContext(ctx, readSidecar, arg.Inode, arg.Device)
	var data string
	err := row.Scan(&data)
	return data, err
}

const removeFileTag = `-- name: RemoveFileTag :exec
DELETE FROM file_tags WHERE file_id = ? AND tag_id = ?
`

type RemoveFileTagParams struct {
	FileID int64 `json:"file_id"`
	TagID  int64 `json:"tag_id"`
}

func (q *Queries) RemoveFileTag(ctx context.Context, arg RemoveFileTagParams) error {
	_, err := q.db.ExecContext(ctx, removeFileTag, arg.FileID, arg.TagID)
	return err
}

const setTagProvenance = `-- name: SetTagProvenance :exec
INSERT INTO tag_provenance(file_id, tag_id, source, set_at)
VALUES (?, ?, ?, ?)
ON CONFLICT(file_id, tag_id) DO UPDATE SET
    source = excluded.source,
    set_at = excluded.set_at
`

type SetTagProvenanceParams struct {
	FileID int64  `json:"file_id"`
	TagID  int64  `json:"tag_id"`
	Source string `json:"source"`
	SetAt  int64  `json:"set_at"`
}

func (q *Queries) SetTagProvenance(ctx context.Context, arg SetTagProvenanceParams) error {
	_, err := q.db.ExecContext(ctx, setTagProvenance,
		arg.FileID,
		arg.TagID,
		arg.Source,
		arg.SetAt,
	)
	return err
}

const upsertFile = `-- name: UpsertFile :one
INSERT INTO files(path, inode, device, mtime, size_bytes, indexed_at)
VALUES (?, ?, ?, ?, ?, ?)
ON CONFLICT(path) DO UPDATE SET
    inode      = excluded.inode,
    device     = excluded.device,
    mtime      = excluded.mtime,
    size_bytes = excluded.size_bytes,
    indexed_at = excluded.indexed_at
RETURNING id
`

type UpsertFileParams struct {
	Path      string `json:"path"`
	Inode     int64  `json:"inode"`
	Device    int64  `json:"device"`
	Mtime     int64  `json:"mtime"`
	SizeBytes int64  `json:"size_bytes"`
	IndexedAt int64  `json:"indexed_at"`
}

func (q *Queries) UpsertFile(ctx context.Context, arg UpsertFileParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, upsertFile,
		arg.Path,
		arg.Inode,
		arg.Device,
		arg.Mtime,
		arg.SizeBytes,
		arg.IndexedAt,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const upsertMeta = `-- name: UpsertMeta :exec
INSERT INTO metadata(file_id, key, value, source)
VALUES (?, ?, ?, ?)
ON CONFLICT(file_id, key) DO UPDATE SET
    value  = excluded.value,
    source = excluded.source
`

type UpsertMetaParams struct {
	FileID int64  `json:"file_id"`
	Key    string `json:"key"`
	Value  string `json:"value"`
	Source string `json:"source"`
}

func (q *Queries) UpsertMeta(ctx context.Context, arg UpsertMetaParams) error {
	_, err := q.db.ExecContext(ctx, upsertMeta,
		arg.FileID,
		arg.Key,
		arg.Value,
		arg.Source,
	)
	return err
}

const upsertTag = `-- name: UpsertTag :one
INSERT INTO tags(name) VALUES (?)
ON CONFLICT(name) DO UPDATE SET name = name
RETURNING id
`

func (q *Queries) UpsertTag(ctx context.Context, name string) (int64, error) {
	row := q.db.QueryRowContext(ctx, upsertTag, name)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const writeSidecar = `-- name: WriteSidecar :exec
INSERT INTO sidecar_data(inode, device, data) 
VALUES (?, ?, ?) 
ON CONFLICT(inode, device) DO UPDATE SET data=excluded.data
`

type WriteSidecarParams struct {
	Inode  int64  `json:"inode"`
	Device int64  `json:"device"`
	Data   string `json:"data"`
}

func (q *Queries) WriteSidecar(ctx context.Context, arg WriteSidecarParams) error {
	_, err := q.db.ExecContext(ctx, writeSidecar, arg.Inode, arg.Device, arg.Data)
	return err
}
